In [1]:
import numpy as np

In [2]:
a = np.array([5,7,8])
b = np.array([2,3,4])

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.vstack([a,b])

array([[5, 7, 8],
       [2, 3, 4]])

In [6]:
np.hstack([a,b])

array([5, 7, 8, 2, 3, 4])

In [7]:
np.pow(a,2)

array([25, 49, 64])

In [9]:
np.sqrt(a)

array([2.23606798, 2.64575131, 2.82842712])

In [10]:
a

array([5, 7, 8])

In [11]:
np.add(a,1)

array([6, 8, 9])

In [12]:
np.dot(a,b)

np.int64(63)

In [14]:
np.ravel([a,b])

array([5, 7, 8, 2, 3, 4])

In [15]:
b

array([2, 3, 4])

In [17]:
np.reshape(a,(3,1))

array([[5],
       [7],
       [8]])

In [21]:
np.mean(a)

np.float64(6.666666666666667)

In [22]:
np.round(np.mean(a))

np.float64(7.0)

In [24]:
np.median(a)

np.float64(7.0)

In [26]:
np.var(b)

np.float64(0.6666666666666666)

In [27]:
np.std(b)

np.float64(0.816496580927726)

In [55]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [51]:
lis = [10,20,30,40,50,10]
np.random.choice(lis,5,replace=True)

array([10, 50, 10, 10, 50])